version: 2.1
orbs:
  python: circleci/python@0.1
  node: circleci/node@1.1.6
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch-node-browsers
      - image: circleci/postgres:10-alpine-postgis
        environment:
          POSTGRES_USER: sampleapp
          POSTGRES_DB: sampleapp
          DATABASE_URL: postgis://sampleapp@localhost:5432/sampleapp
      - image: circleci/redis     
    working_directory: /home/circleci/project
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache

      - node/with-cache:
          steps:
            - run: yarn install --frozen-lockfile

      - run: sudo apt-get install -y postgresql-client
      - run: ./test.sh 
      - run: cd ../sampleapp
      - run: circleci local execute --job test
      

workflows:
  version: 2.1
  test:
    jobs:
      - build:
          context: lightmatter
      - test_default:
          context: lightmatter
          depends:
            build
